Fix Cookie -> WebDriverCookie same_site parsing
Fetching all cookies from fantoccini client and loading
them back reveals that same_site is not properly parsed
when converting from Cookie -> WebDriverCookie.

For example, client.get_all_cookies() can return both
the following same_site values in different cookies, the
second of which is transformed by the map call into an
Option::None which gets ignored by WebDriverCookie serde
skip_serializing_if = "Option::is_none":

same_site: Some(
        None,
    ),

same_site: None,

An example error when calling client.add_cookie() with the
above "same_site: None":

thread 'main' panicked at 'called `Result::unwrap()` on an
`Err` value: Standard(WebDriver { error: InvalidArgument,
message: "invalid argument: invalid 'sameSite'\n
(Session info: chrome=98.0.4758.80)"

This fixes the error by parsing the top-level None value
to a None string as expected by WebDriverCookie.